### ISSUE TITLE
Latest Posts

### ISSUE THREAD

**Issue by sebelk** [getgrav/grav-theme-notepad#10]
When I click on "Read More" at Latest Posts, pages list is not shown.

However, I have posts below:

```
user/pages/blog/
├── 15-11-2016
│   └── post.md
├── 2013-12-30-readability-feature-post
│   ├── post.md
│   └── tokyo.jpg
├── 2014-01-08-a-quotation
│   ├── albert-einstein-2068-hd-wallpapers.jpg
│   └── post.md
├── 2014-01-10-theme-elements
│   ├── photo13.jpg
│   ├── photo16.jpg
│   ├── photo19.jpg
│   ├── picture-38.jpg
│   └── post.md
├── 2014-05-15-first-commit
│   ├── cover9.jpg
│   └── post.md
├── 2014-08-12-sample-link-post
│   └── page.md
├── 2014-11-30-why-grav
│   ├── post.md
│   ├── stuff.jpg
│   └── swim.jpg
├── 2016-10-30-ejemplo-sergio.md
│   └── post.md
├── 2016-10-30-Semana-31
│   ├── post.md
│   ├── stuff.jpg
│   └── swim.jpg
├── 2016-10-30-Semana-31-10
│   ├── post.md
│   ├── stuff.jpg
│   └── swim.jpg
├── comienzo-de-semana-del-7-11-16
│   └── post.md
├── planificacion-04-10-2016
│   └── post.md
├── planificacion-13-11-2016
│   └── default.md
├── planificacion-semana-14-11-2016
│   └── default.md
├── planificacion-verano
│   └── post.md
├── post.md
└── pxe
    └── post.md
```

What's could be wrong?

If you need I could post some config file.

Thanks in advance!

**Comment by sebelk** [comment]
I've fixed, the file /var/www/cms/user/pages/blog/post.md  had single quotes around @self.children , now is as  follows and works:

```

---
title: 'Mis Posts'
sitemap:
    changefreq: monthly
    priority: 1.03
content:
    items: @self.children
    order:
        by: date
        dir: desc
    limit: 4
    pagination: true
feed:
    description: 'Sample Blog Description'
    limit: 10
pagination: true
---
```

It seems that Admin Panel introduced such error...
